filename: "mock_{{.InterfaceName}}_test.go"
force-file-write: true
dir: ./
structname: Mock{{.InterfaceName}}
pkgname: collector
template: testify
packages:
  github.com/godepo/elephant:
    config:
      all: false
    interfaces:
      Counter: {}
      Histogram: {}
