// Code generated by mockery v2.53.3. DO NOT EDIT.

package collector

import (
	elephant "github.com/godepo/elephant"
	mock "github.com/stretchr/testify/mock"
)

// MockCounterCollector is an autogenerated mock type for the CounterCollector type
type MockCounterCollector struct {
	mock.Mock
}

type MockCounterCollector_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCounterCollector) EXPECT() *MockCounterCollector_Expecter {
	return &MockCounterCollector_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: labels
func (_m *MockCounterCollector) Execute(labels ...string) (elephant.Counter, error) {
	_va := make([]interface{}, len(labels))
	for _i := range labels {
		_va[_i] = labels[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 elephant.Counter
	var r1 error
	if rf, ok := ret.Get(0).(func(...string) (elephant.Counter, error)); ok {
		return rf(labels...)
	}
	if rf, ok := ret.Get(0).(func(...string) elephant.Counter); ok {
		r0 = rf(labels...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(elephant.Counter)
		}
	}

	if rf, ok := ret.Get(1).(func(...string) error); ok {
		r1 = rf(labels...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCounterCollector_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockCounterCollector_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - labels ...string
func (_e *MockCounterCollector_Expecter) Execute(labels ...interface{}) *MockCounterCollector_Execute_Call {
	return &MockCounterCollector_Execute_Call{Call: _e.mock.On("Execute",
		append([]interface{}{}, labels...)...)}
}

func (_c *MockCounterCollector_Execute_Call) Run(run func(labels ...string)) *MockCounterCollector_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]string, len(args)-0)
		for i, a := range args[0:] {
			if a != nil {
				variadicArgs[i] = a.(string)
			}
		}
		run(variadicArgs...)
	})
	return _c
}

func (_c *MockCounterCollector_Execute_Call) Return(_a0 elephant.Counter, _a1 error) *MockCounterCollector_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCounterCollector_Execute_Call) RunAndReturn(run func(...string) (elephant.Counter, error)) *MockCounterCollector_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCounterCollector creates a new instance of MockCounterCollector. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCounterCollector(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCounterCollector {
	mock := &MockCounterCollector{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
