dir: ./
structname: Mock{{.InterfaceName}}
pkgname: elephant
template: testify
force-file-write: true
packages:
  github.com/jackc/pgx/v5:
    config:
      all: false
      include-interface-regex: Tx
