with-expecter: True
dir: ./
mockname: "Mock{{.InterfaceName}}"
filename: "mock_{{.InterfaceName}}_test.go"
outpkg: "singlepg"
packages:
  github.com/godepo/elephant/internal/cluster:
    config:
      all: False
    interfaces:
      Pool:
        config:
  github.com/jackc/pgx/v5:
    config:
      all: False
      include-regex: "Tx"
