filename: "mock_{{.InterfaceName}}_test.go"
dir: ./
structname: Mock{{.InterfaceName}}
pkgname: singlepg
template: testify
force-file-write: true
packages:
  github.com/godepo/elephant/internal/cluster:
    config:
      all: false
    interfaces:
      Pool: {}
  github.com/jackc/pgx/v5:
    config:
      all: false
      include-interface-regex: Tx

