filename: "mock_{{.InterfaceName}}_test.go"
dir: ./
structname: Mock{{.InterfaceName}}
pkgname: shardedpg
template: testify
force-file-write: true
packages:
  github.com/godepo/elephant/internal/sharded:
    config:
      all: false
    interfaces:
      Pool: {}
  github.com/jackc/pgx/v5:
    config:
      all: false
    interfaces:
      Tx: {}
      Row: {}
      Rows: {}