dir: ./
structname: Mock{{.InterfaceName}}
pkgname: acceptance
template: testify
force-file-write: true
packages:
  github.com/godepo/elephant/internal/metrics:
    config:
      all: false
    interfaces:
      Collector: {}
      Pool: {}
