filename: "mock_{{.InterfaceName}}_test.go"
dir: ./
structname: Mock{{.InterfaceName}}
pkgname: regular
template: testify
force-file-write: true
packages:
  github.com/godepo/elephant/internal/regular:
    config:
      all: false
    interfaces:
      DB: {}
      Pool: {}
  github.com/jackc/pgx/v5:
    config:
      all: false
    interfaces:
      Rows: {}
      Tx: {}
