dir: ./
structname: Mock{{.InterfaceName}}
pkgname: clusterpg
template: testify
filename: mocks_{{.InterfaceName}}_test.go
force-file-write: true
packages:
  github.com/godepo/elephant/internal/cluster:
    config:
      all: false
    interfaces:
      DB: {}
      Pool: {}
  github.com/jackc/pgx/v5:
    config:
      all: false
    interfaces:
      Rows: {}
      Tx: {}
      Row: {}
