dir: ./
structname: Mock{{.InterfaceName}}
pkgname: metrics
template: testify
filename: mocks_{{.InterfaceName}}_test.go
force-file-write: true
packages:
  github.com/godepo/elephant/internal/metrics:
    config:
      all: false
    interfaces:
      Collector: {}
      Pool: {}
